name: Update Publications

on:
  schedule:
    - cron: '0 1 * * *'  # Every night at 01:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Zotero to Markdown script
        run: python scripts/generate_publications.py

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet docs/publications.md; then
            echo "No changes to commit."
          else
            git add docs/publications.md
            git commit -m "Update publications from Zotero"
            git push
          fi

